### ISSUE TITLE
What is this?!?

### ISSUE THREAD

**Issue by chavenor** [mobileoverlord/kiosk_web_engine#1]
@mobileoverlord -- dude this just popped up in my feed and I'm stoked.  Can you elaborate on what this actually is?

**Comment by mobileoverlord** [comment]
My goal for `Kiosk.WebEngine` is to provide a layer of supervision and control over the instance of chromium that is built into the `kiosk_system_*` Nerves systems.

[kiosk_system_rpi3](https://github.com/LeToteTeam/kiosk_system_rpi3)
[kiosk_system_x86_64](https://github.com/LeToteTeam/kiosk_system_x86_64)

This application will 
  * supervise the `qt-webengine-kiosk` app.
  * enable full RPC control over the chromium page
  * include a progress page to render messages for boot / software updates / shutdown
 
The idea is to draft up a series of recipes for building interactive kiosk devices using Elixir.

**Comment by chavenor** [comment]
That is awesome.   I will be learning Elixir immediately.  This put me over the edge.  Some much cool stuff happening in this space.
